// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkhloafmzvowtdgfibxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraGxvYWZtenZvd3RkZ2ZpYnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjM2NDQsImV4cCI6MjA3Mjk5OTY0NH0.2FXG5DT7qhPsH0nZkJRdSswtlOjiSHq_kx74AOHcMzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});